spring.data.mongodb.uri=mongodb+srv://escrowUser:Amar12345@cluster0.xo8iygk.mongodb.net/escrowDB?retryWrites=true&w=majority
spring.data.mongodb.database=escrowDB

server.port=${PORT:9090}

jwt.secret=your_super_secret_key_which_should_be_long_enough_1234567890
jwt.expiration=86400000

# ? DISABLE DEFAULT SPRING SECURITY USER
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration


razorpay.key.id=rzp_test_SKs3BIK0Y74ouv
razorpay.key.secret=RKn1yU1GWxxsudVxhmoN2OfO