spring.data.mongodb.uri=mongodb+srv://escrowUser:Amar12345@cluster0.xo8iygk.mongodb.net/escrowDB?retryWrites=true&w=majority
spring.data.mongodb.database=escrowDB

server.port=${PORT:9090}

jwt.secret=mySuperSecretKeyForJwtToken123456
jwt.expiration=86400000

# ? DISABLE DEFAULT SPRING SECURITY USER
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration




# EMAIL CONFIG
spring.mail.host=smtp-relay.brevo.com
spring.mail.port=587
spring.mail.username=a45693001@smtp-brevo.com
spring.mail.password=xsmtpsib-b2531a8e850149fb04920c803b8ed3aca943b30ecc64404e34c9b725618fded0-Suj880oGtJxD58y9

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
